name: Go build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'stable', 'oldstable' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Fetch deps
        run: make -f ci/Makefile deps
      - name: Build
        run: make -f ci/Makefile build
      - name: Test
        run: make -f ci/Makefile test
